/*already admitted
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MiniProject_HospitalManagementSystem;

/**
 *
 * @author WIN
 */
public class Already_admitted extends javax.swing.JFrame {

    /**
     * Creates new form Already_admitted
     */
    public Already_admitted() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Patient_ad = new javax.swing.JButton();
        Patient_dis = new javax.swing.JButton();
        billing_pat = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Already Admitted");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Patient_ad.setText("Patient admit Details");
        Patient_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_adActionPerformed(evt);
            }
        });
        getContentPane().add(Patient_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 139, -1, -1));

        Patient_dis.setText("Patient Discharge");
        Patient_dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_disActionPerformed(evt);
            }
        });
        getContentPane().add(Patient_dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 198, 131, -1));

        billing_pat.setText("Billing of Patient");
        billing_pat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billing_patActionPerformed(evt);
            }
        });
        getContentPane().add(billing_pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 263, 131, -1));

        back.setText("<-  Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\WIN\\Documents\\NetBeansProjects\\MiniProject_HospitalManagementSystem_trial\\build\\classes\\MiniProject_HospitalManagementSystem\\already_admitted.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -80, 500, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Patient_section obj=new Patient_section();
            obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_backActionPerformed

    private void Patient_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_adActionPerformed
        // TODO add your handling code here:
        Patient_Admit_Details obj=new Patient_Admit_Details();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Patient_adActionPerformed

    private void Patient_disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_disActionPerformed
        // TODO add your handling code here:
                Patient_Discharge_Room obj=new Patient_Discharge_Room ();
                obj.setVisible(true);
                dispose();
    }//GEN-LAST:event_Patient_disActionPerformed

    private void billing_patActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billing_patActionPerformed
        // TODO add your handling code here:
                Patient_Bill obj=new Patient_Bill();
                obj.setVisible(true);
                dispose();
    }//GEN-LAST:event_billing_patActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Already_admitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Already_admitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Already_admitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Already_admitted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Already_admitted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Patient_ad;
    private javax.swing.JButton Patient_dis;
    private javax.swing.JButton back;
    private javax.swing.JButton billing_pat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
