/*patient form
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MiniProject_HospitalManagementSystem;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.math.BigInteger;

/**
 *
 * @author WIN
 */
public class Patient_form extends javax.swing.JFrame {

    /**
     * Creates new form Module1
     */
    public Patient_form() {
        initComponents();
        showDate();
        showTime();
    }

    void showDate(){
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("yyy-MM-dd");
        datelab.setText(s.format(d)); 
    }
    
    void showTime(){
          new Timer(0,new ActionListener() {
              @Override
              public void actionPerformed(ActionEvent e) {
                  Date d=new Date();
                  SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
                  timelab.setText(s.format(d));
                  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
              }
          }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        ill = new javax.swing.JComboBox<>();
        doctor = new javax.swing.JComboBox<>();
        PI = new javax.swing.JTextField();
        CD = new javax.swing.JTextField();
        datelab = new javax.swing.JLabel();
        timelab = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("PATIENT FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel2.setText("Enter the Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setText("Patient Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel4.setText("Father Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel5.setText("Phone  Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 80, 10));

        jLabel6.setText("Patient Illness:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel7.setText("Choose Doctor: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));
        getContentPane().add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 340, -1));
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 340, -1));

        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });
        getContentPane().add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 340, -1));

        ill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fever", "Flu", "BloodPressure", "Cancer", "Tumor" }));
        ill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                illActionPerformed(evt);
            }
        });
        getContentPane().add(ill, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. David", "Dr. Thompson", "Dr. Vivek", "Dr. Tina", "Dr. Hassan" }));
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));
        getContentPane().add(PI, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 220, -1));
        getContentPane().add(CD, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 220, -1));

        datelab.setText("Date:");
        getContentPane().add(datelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        timelab.setText("Time:");
        getContentPane().add(timelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jLabel8.setText("Go Back");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 50, 30));

        jButton2.setText("Admit patient ?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","Hinal@12345");
           String s1="insert into new_patient values(?,?,?,?,?)";
           PreparedStatement st=con.prepareStatement(s1);
           st.setString(1,pn.getText());
           st.setString(2,fn.getText());
           st.setString(3,phoneno.getText());
           st.setString(4,ill.getSelectedItem().toString());
           st.setString(5,doctor.getSelectedItem().toString());
           JOptionPane.showMessageDialog(null,"Data inserted successfully");
           con.close();
           /*PI.setText(ill.getSelectedItem().toString());
           CD.setText(doctor.getSelectedItem().toString());*/
           pn.setText("");
           fn.setText("");
           phoneno.setText("");
           PI.setText("");
           CD.setText("");
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Patient_section obj=new Patient_section();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void illActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_illActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_illActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Patient_Admit_Room obj=new Patient_Admit_Room();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CD;
    private javax.swing.JTextField PI;
    private javax.swing.JLabel datelab;
    private javax.swing.JComboBox<String> doctor;
    private javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> ill;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTextField pn;
    private javax.swing.JLabel timelab;
    // End of variables declaration//GEN-END:variables
}
